### ISSUE TITLE
Allow account creation based on email for caprover pro, pricing?

### ISSUE THREAD

**Issue by genox** [caprover/caprover-pro#4]
Hi,

I would like to consider caprover pro.

But: I don't use third party auth providers for critical infrastructure. Please consider offering email-based account creation.

And I can't find any pricing information. :)

All the best and thanks.

**Comment by githubsaturn** [comment]
Right now, only google auth is supported because of the built in security features. Email will be added in the future. But it's far from reality that our own email auth can exceed in reliability and security compared to Google. 

Pricing can be found after you log in.

**Comment by JakubJeziorski** [comment]
For those who are looking for Caprover Pro pricing:
Pro Plan
$2.99 per month ($1.99 per month when paid annually) 
Everything that Free has, plus:

    Two-factor authentication:
    Proactive login monitoring
    Build failure and success monitoring
    Up to 5 instances per license
    Email support (24hr SLA)
    More to come!
    
My questions is: What are instances? Individual apps or servers?

**Comment by githubsaturn** [comment]
Servers

**Comment by blee0518** [comment]
@githubsaturn I know its an old comment. but have you considered the email verification? I can have someone from my team help out and mailgun or sendgrid provides free tier email verification services.

**Comment by genox** [comment]
I have since moved on to another solution, I suggest you make a new issue if you are hell bent on getting this into cap rover.

**Comment by Boscop** [comment]
@genox I'm curious, which other solution have you moved to? :)

**Comment by genox** [comment]
> @genox I'm curious, which other solution have you moved to? :)

https://coolify.io
